spring:
 application :
  name : employee-service
 datasource:
  driver-class-name: org.h2.driver
#  url: jdbc:postgresql://localhost:5432/d
  username: karani-dev
  password: felixmaina

 jpa:
#  properties:
#    hibernate:
#     dialect: org.hibernate.dialect.PostgreSQLDialect
#     format_sql: true
  hibernate:
   ddl-auto: create
  show-sql: true
  database-platform: org.hibernate.dialect.H2Dialect
 sql :
  init:
   mode: always
server:
    port: 8066


eureka:
 client:
  serviceUrl:
    defaultZone: http://localhost:8761/eureka

management:
 tracing:
  sampling:
   probability: 1.0





